USE ROLE ACCOUNTADMIN;

CREATE WAREHOUSE IF NOT EXISTS DBT_WH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;

CREATE DATABASE IF NOT EXISTS NEW_YORK_TAXI;

CREATE ROLE IF NOT EXISTS NYC_TAXI_ROLE;

GRANT USAGE, OPERATE, MONITOR ON WAREHOUSE DBT_WH TO ROLE NYC_TAXI_ROLE;

GRANT ROLE NYC_TAXI_ROLE TO USER SPA0424;

SHOW GRANTS ON WAREHOUSE DBT_WH;

GRANT ALL ON DATABASE NEW_YORK_TAXI TO ROLE NYC_TAXI_ROLE;

CREATE SCHEMA IF NOT EXISTS NEW_YORK_TAXI.NYC_TAXI;

SHOW GRANTS TO ROLE NYC_TAXI_ROLE;

USE ROLE NYC_TAXI_ROLE;
USE WAREHOUSE DBT_WH;
USE DATABASE NEW_YORK_TAXI;
USE SCHEMA NYC_TAXI;
